id: P7228176F
initial_creation_type: input
source_metadata:
  title: Parting from the Four Attachments
  language: fr
  description: 'A series of texts related to the famous four-line instruction that
    Sachen Kunga Nyingpo (1092–1158) received from Mañjuśrī:'
  volume:
    4c3639dcdaa241ac82e68918f3ac06ca:
      title: Supplement to the Omniscient Ngorchen Kunga Zangpo’s Prayer to the Lineage
        of Parting from the Four Attachments
      parent: Lineage Prayers
    d86fa3fc78fe41c0b10e6f7c8e5337df:
      title: Prayer to the Lineage of Parting from the Four Attachments
      parent: Lineage Prayers
    93084e95c00947d3a98c4875d3efec86:
      title: The Instructions on Parting from the Four Attachments
      parent: Root Text
    f3a39c45eccf425fa7a894d285f5e69d:
      title: Parting from the Four Attachments
      parent: Commentaries
    3a1b0bf5cf174c35aaacae9ed9963b63:
      title: Nubpa Rigdzin Drak's Parting from the Four Attachments
      parent: Commentaries
    025cecb05f0949f8b6c1099b7398284b:
      title: Sakya Paṇḍita’s Instruction on Parting from the Four Attachments
      parent: Commentaries
    14ce652ec3e5492eacb2b83155900ded:
      title: 'Nectar of the Heart: An Experiential Song of Parting from the Four Attachments'
      parent: Song
created_at: '2022-03-01T05:02:13.482027'
last_modified_at: '2022-03-01T05:02:13.482029'
